SELECT P.PACKAGE_ID --, C.CONTAINER_ID, C.CONTAINER_STATUS_CD, TH.EVENT_CD
FROM SPTRPRT_SCHEMA.PACKAGE P
JOIN SPTRPRT_SCHEMA.CONTAINER C ON C.CONTAINER_ID = P.CONTAINER_ID AND C.CONTAINER_STATUS_CD IN ('DELIVERED', 'DISPATCHED')
                                   AND SUBSTR(C.CONTAINER_ID,0,2) = 'PP'
JOIN SPTRPRT_SCHEMA.TRIP_STOP TS ON C.TRIP_STOP_SEQ = TS.TRIP_STOP_SEQ
JOIN SPTRPRT_SCHEMA.TRIP T ON TS.TRIP_SEQ = T.TRIP_SEQ
JOIN SPTRPRT_SCHEMA.TRIP_HISTORY TH ON T.TRIP_SEQ = TH.TRIP_SEQ AND TH.EVENT_CD = 'TripDispatch'
WHERE P.PACKAGE_ID in (:pkgList)