SELECT PKG_ID, CHANL_APP_ID, UNMAN_STAT, PTS_XMT_DT, SCAN_DT, PSTG_AMT,  CLIENT_MAILER_ID,
       CLIENT_MAILER_NM, SCAN_FAC_PSTL_CD, RECT_SRC, MAIL_CLASS
FROM SPEVS_SCHEMA.UNMANIFESTED_PACKAGE
WHERE PKG_ID IN (:packageIds)