SELECT PKG_ID, EVS_MANIFEST_SEQ, ERROR_CD, MAIL_CLASS, ACTL_WGT, DEST_ZIP, CNTRY_CODE, PRCS_CTG,
       DEST_RATE_IND, RATE_IND, ZONE, BARCODE_CD, PROD_CD, ARTICLE_VALUE, LENGTH, WIDTH, HEIGHT,
       DIM_WGT, CLIENT_MAILER_ID, CUST_REF_NBR, ENTRY_FAC_ZIP, TRLR_CLOSE_DT, HUB_ID, SENT_EVS_FLAG,
       CUR_DT_TM_STAMP, OVSZ_FLAG, BLN_FLAG, DC_FLAG, COD_FLAG, ERR_MSG, FIELD_ERR_MSG, ERR_LINE_NBR,
       USER_LOAD_NBR, EVS_RELEASE_TYPE_CD, TRIP_SEQ, CHANL_APP_ID, SERVICE_TYPE_CD, ENTRY_FAC_TYPE_CD,
       FAST_RSVTN_NBR, FAST_SCHEDULED_DT, CONTAINER_ID, CONTAINER_TYPE_CD, MAIL_DATE_TMSTP,
       SUPPRESS_PSTG_FLAG, SUPPRESS_PSTG_RSN_CD, MAIN_ELEC_FILE_NBR, RATE_SHEET_LABEL_TXT,
       ZIP_LIST_LABEL_TXT, ALLOCATE_HUB_ID, PAYMENT_ACCT_NBR, RATING_RLS_RCVD_DT
FROM SPEVS_SCHEMA.PACKAGE WHERE PKG_ID IN (:packageIds)