SELECT FEDEX_PKG_ID,FEDEX_CUST_ACCT_NBR,HANDLE_FLAG,PKG_CATEGORY_CD,PKG_TYPE_CD,
	   CUST_DIST_CTR,CUST_MNFST_ID,SP_PKG_WGT,SP_PKG_HGT,SP_PKG_LENGTH,SP_PKG_WIDTH,
	   SP_PKG_WGT_SOURCE_CD,SP_PKG_DIM_SOURCE_CD,CUST_PKG_WGT,CUST_PKG_HGT,
	   CUST_PKG_LENGTH,CUST_PKG_WIDTH,PSTL_CLASS_CD,PSTL_SUB_CLASS_CD,ORIGIN_HUB_CD,
	   ORIGIN_PSTL_CD,RECP_PSTL_CD,CUST_PKG_ID,SP_BLNG_SVC_CD,DEL_CON_REQ_FLAG,
	   EPDI_AUDIT_FLAG,EXPECTED_FLAG,PKG_RCV_FLAG,BILLING_NBR,MNFST_GRP_TEXT,
	   FXG_SVC_CD_SRC,CHANL_APP_ID,PO_NUM,METER_NUM,RMA_NUM,TPTY_FEDEX_CUST_ACCT_NBR,
	   DEL_CONF_REQD_FLAG_SRC,FEDEX_CUST_ACCT_NBR_SRC,MAILER_ID,LABEL_FMT,RETURN_TYP,
	   CUST_MAIL_CLASS_CD,CUST_SUB_MAIL_CLASS_CD,CUST_FXG_HUB_ID
FROM sprods_schema.BILLING_PACKAGE_HISTORY
WHERE FEDEX_PKG_ID IN (:packageIds)
